name: Build and Push to ACR

on:
   push:
       branches:
         - master

jobs:
     build-and-push:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Log in with Azure
         uses: azure/login@v1
         with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
         
       - name: Build and push Docker image
         run: |
           docker buildx create --use
           docker buildx build --platform linux/amd64 -t azurecontainerkrss.azurecr.io/myimage:latest .
           docker login azurecontainerkrss.azurecr.io 
           docker push azurecontainerkrss.azurecr.io/myimage:latest
